In [ ]:
# 1. Self-attention by hand
# 2. Self-attention block in pytorch
# 3. GPT, piece-by-piece
# 4. GPU goes rrrr!

### Step 1: Self-attention by hand

In [1]:
import numpy as np

c:\Users\elelo\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\elelo\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\Users\elelo\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [ ]:
#  -- Write the scaled dot product self attention
  # 1. Compute queries, keys, and values
  # 2. Compute dot products
  # 3. Scale the dot products
  # 4. Apply softmax to calculate attentions
  # 5. Weight values by attentions
  # 6. Compute attention weighted features

In [14]:
# Choose values for the parameters
# Do not modify this code

X = np.array([[2,0,0,2],[0,1,0,0],[0,2,1,0],[0,0,1,1],[2,0,0,0],[1,0,1,1]], dtype=float)
W_Q = np.array([[1,1,0,0,0,0],[0,1,0,1,0,0],[0,0,1,0,1,1]], dtype=float)
W_K = np.array([[0,0,1,0,0,0],[0,1,0,0,0,0],[1,0,0,0,0,-1]], dtype=float)
W_V = np.array([[10,0,0,0,0,0],[0,0,0,10,0,0],[0,10,0,0,0,0]], dtype=float)

Q = W_Q @ X
K = W_K @ X
V = W_V @ X

In [27]:
# What does the first dimension of matrices Q and K correspond to?
# Dq = 3

In [16]:
# This is given for you. Do not modify this code.
def softmax_cols(data_in):
  # Exponentiate all of the values
  exp_values = np.exp(data_in)
  # Sum over columns
  denom = np.sum(exp_values, axis = 0)
  # Replicate denominator to N rows
  denom = np.matmul(np.ones((data_in.shape[0],1)), denom[np.newaxis,:])
  # Compute softmax
  softmax = exp_values / denom
  # return the answer
  return softmax

In [34]:
# compute the weighted attention matrix S
S = softmax_cols((K.T @ Q)/np.sqrt(Q.shape[0]))


In [35]:
# compute the self-attention matrix A
A = V @ S

In [36]:
A

array([[10.30759701, 10.10551833, 15.03361159,  3.06082018],
       [ 2.83283874,  2.97334971,  4.13169018,  1.53041009],
       [ 4.59026201,  4.50027071,  2.10990693,  7.70438486]])

In [37]:
# Sanity check. This should return True.
np.allclose(A, np.array([[10.30759701, 10.10551833, 15.03361159,  3.06082018],
       [ 2.83283874,  2.97334971,  4.13169018,  1.53041009],
       [ 4.59026201,  4.50027071,  2.10990693,  7.70438486]]))

True

### Step 2: Self-attention block in pytorch

In [29]:
import torch
import torch.nn as nn
from torch.functional import F

In [58]:
# do not modify this code

batch_size = 3 # B
block_size = 2 # T (N)
n_embd = 3     # C (D)

In [59]:
torch.set_printoptions(precision=8)

In [63]:
# Build a scaled self-attention head without masked attention and without dropout (i.e. just key, query and values)
# A matrix multiplication is implemented using the nn.Linear() operator with no bias.

# head_size : dim des matrices de poids W (head_size * n_embed)

class Head(nn.Module):

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False) # produit matriciel lineaire simple
        self.query = nn.Linear(n_embd, head_size, bias=False) 
        self.values = nn.Linear(n_embd, head_size, bias=False)

    def forward (self, x):
        B, T, C = x.shape
        K = self.key(x)
        Q = self.query(x)
        V = self.values(x)
        
        wei = (Q @ K.transpose(-2,-1))*C**-0.5 # pour pas transposer sur le batch, (transpose(1,2) et pas prendre en compte le batch)
        wei = F.softmax(wei, dim=-1)
        out = wei @ V
        return out

In [64]:
# Unit test. Do not modify this code
torch.manual_seed(123) # do not remove this line
h = Head(2)
torch.manual_seed(123) # do not remove this line
x = torch.rand((batch_size, block_size, n_embd))
out = h(x)
out

tensor([[[-0.46653441,  0.03306433],
         [-0.47224301,  0.04610372]],

        [[-0.38105938,  0.02397405],
         [-0.39453450,  0.02482041]],

        [[-0.29578221,  0.12158968],
         [-0.30042297,  0.12526260]]], grad_fn=<UnsafeViewBackward0>)

In [65]:
# Sanity check. This should return True.
torch.allclose(out, torch.tensor([[[-0.46653444,  0.03306433],
         [-0.47224304,  0.04610372]],
        [[-0.38105938,  0.02397406],
         [-0.39453450,  0.02482042]],
        [[-0.29578221,  0.12158968],
         [-0.30042297,  0.12526260]]]))

True

In [68]:
# Add weighted masked attention and dropout. Dropout comes after the softmax and before the multiplication with the value matrix.
# Copy the Head class from the previous exercise and expand upon it.

class Head(nn.Module):

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False) # produit matriciel lineaire simple
        self.query = nn.Linear(n_embd, head_size, bias=False) 
        self.values = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size))) # store a persistent buffer for the forward pass

    def forward (self, x):
        B, T, C = x.shape
        K = self.key(x)
        Q = self.query(x)
        V = self.values(x)
        
        wei = (Q @ K.transpose(-2,-1))*C**-0.5 # pour pas transposer sur le batch, (transpose(1,2) et pas prendre en compte le batch)
        wei = wei.masked_fill(self.tril[:T,:T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        out = wei @ V
        return out

In [69]:
# Unit test. Do not modify this code
torch.manual_seed(123) # do not remove this line
h = Head(2)
torch.manual_seed(123) # do not remove this line
x = torch.rand((batch_size, block_size, n_embd))
out = h(x)
out

tensor([[[-0.37939817, -0.16596894],
         [-0.47224301,  0.04610372]],

        [[-0.14184165,  0.00894911],
         [-0.39453450,  0.02482041]],

        [[-0.17301908,  0.02442870],
         [-0.30042297,  0.12526260]]], grad_fn=<UnsafeViewBackward0>)

In [70]:
# Sanity check. This should return True.
torch.allclose(out, torch.tensor([[[-0.37939820, -0.16596894],
         [-0.47224304,  0.04610372]],
        [[-0.14184165,  0.00894911],
         [-0.39453450,  0.02482042]],
        [[-0.17301908,  0.02442869],
         [-0.30042297,  0.12526260]]]))


True

In [82]:
# A multi-head attention module contains a list of heads and a linear projection layer.
# The heads are applied to the input and then concatenated along the last dimension, then
# the linear layer is applied. Look at the unit test below to determine the dimensions of
# the linear layer.

class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for i in range(num_heads)]) # on compute chaque head pour le nombre  voulue de head
        self.lm = nn.Linear(n_embd, n_embd) # prend en entrée une matrice dont la dim est n_emb


    def forward (self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.lm(out)
        return out

In [83]:
# do not modify
num_heads = 3
head_size = 2
n_embd = 6

In [84]:
# Unit test. Do not modify this code
torch.manual_seed(123) # do not remove this line
sa = MultiHeadAttention(num_heads=3, head_size=head_size)
torch.manual_seed(123) # do not remove this line
x = torch.rand((batch_size, block_size, n_embd))
out = sa(x)

In [85]:
# Sanity check. This should return True.
torch.allclose(out, torch.tensor([[[-0.03730504, -0.07006130, -0.27096999,  0.13144857, -0.45049590,
          -0.33217290],
         [-0.06794342, -0.04509801, -0.34738648,  0.15599491, -0.45456851,
          -0.33087400]],
        [[-0.08914752, -0.03846309, -0.36569631,  0.09802882, -0.39963537,
          -0.29225215],
         [-0.04709741,  0.01406255, -0.25430590,  0.08396727, -0.41786054,
          -0.30781299]],
        [[ 0.15234883, -0.08591781, -0.10099770,  0.19886394, -0.49236685,
          -0.43605998],
         [ 0.15425430, -0.01792544, -0.00511202,  0.14046597, -0.48078871,
          -0.40730378]]]))


True

In [86]:
# Add a classical feedforward module: linear -> ReLU -> linear
# The hidden dimension is four times bigger than the input dimension (see Section 3.3 of Attention is All You Need)
#
class FeedForward(nn.Module):
    """ a simple linear layer followed by a non-linearity """
    def __init__(self, n_embd):
        super().__init__()
        ???

    def forward(self, x):
        out = ???
        return out

SyntaxError: invalid syntax (Temp/ipykernel_16112/2197631140.py, line 11)

In [ ]:
# Unit test. Do not modify this code
torch.manual_seed(123) # do not remove this line
ff = FeedForward(n_embd)
torch.manual_seed(123) # do not remove this line
x = torch.rand((3,n_embd))
out = ff(x)
out

In [ ]:
# Sanity check. This should return True.
torch.allclose(out, torch.tensor([[-0.58034140,  0.04641046, -0.10707694,  0.21581653, -0.30361831,
         -0.07352637],
        [-0.48917407,  0.07879593, -0.15972012,  0.17862344, -0.37070659,
         -0.07852858],
        [-0.48530388,  0.09604470, -0.06524836,  0.16611034, -0.35499069,
         -0.08964306]]))

In [ ]:
# Build a self-attention block
#
#   in -----> LayerNorm -------> multi-head attention -- + ----> LayerNorm -----> FeedForward --- + -----> out
#         |                                              |   |                                    |
#          ----------------------------------------------     ------------------------------------                       
#
# This architecture is slightly different from Attention is All You Need (or the UDL textbook):
# the layer norm comes before (not after) the attention or feed-forward
#
class Block(nn.Module):

    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head
        ???

    def forward(self, x):
        out = ???
        return out

In [ ]:
# Unit test. Do not modify this code
torch.manual_seed(123) # do not remove this line
bk = Block(n_embd, num_heads)
torch.manual_seed(123) # do not remove this line
x = torch.rand((batch_size,block_size,n_embd))
out = bk(x)
out

In [ ]:
# Sanity check. This should return True.
torch.allclose(out, torch.tensor([[[-0.05278997, -0.10863629, -0.09458938,  0.97590691, -0.55101192,
           0.57085067],
         [-0.17928867, -0.44799608, -0.26547045,  1.11293721, -0.34837404,
           0.40728986]],
        [[-0.41515028, -0.30126408, -0.11399293,  0.64651299, -0.51579159,
           0.57017863],
         [-0.02734703,  0.08873296,  0.65776664,  0.70304352,  0.05667025,
           0.70008957]],
        [[ 0.52881187,  0.34458166,  0.31130391,  1.11564195,  0.37998506,
          -0.02971917],
         [ 1.39032197,  0.58906519,  0.97761846,  0.38604784,  0.63349819,
           0.50254500]]]))

In [ ]:
## Step 3: Build a mini GPT
#
# - Start from the gpt-problem.py file
# - Add your Head, MultiHeadAttention, FeedForward and Block classes
# - Fill in the GPT class (__init__ and forward methods)
# - Train the network on CPU
# - Train the network on GPU

# For __init__, the GPT model parameters are:
#   - a token embedding table
#   - a positional embedding table
#   - a sequence of Blocks
#   - a layer norm
#   - a linear layer
#
# For forward(), the model consists in:
#   - applying the token embedding table and positional embedding table to the input tensor
#   - adding the two together
#   - applying the blocks, layer norm and linear layer (in that order)
#
# The code comes from hyperparameters that should work well on GPU.  On CPU, you 
# will need to reduce the model size significantly.
#
# In pytorch, an learnable embedding table is implemented with nn.Embedding(...)
#
# The token embedding table learns an embedding for each item of the vocabulary. The 
# positional embedding table does not depend on the input and learns an embedding
# for each position in the context.